governance:
  - ProphetXZ
  core:
  - ProphetXZ
erc:
  - ProphetXZ
networking:
  - ProphetXZ
interface:
  - lightclient
  - axic
  - SamWilsn
  - Pandapip1
meta:
  - X
informational:
  - lightclient
  - axic
  - gcolvin
  - SamWilsn
  - Pandapip1
  - g11tech
